# Generated by Django 4.1.7 on 2023-04-14 15:52

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(blank=True, help_text='+57', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('cliente', 'Cliente')], max_length=58, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Max 150 caracteres. Letras, numeros y @ / . / + / - / _ .', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
